name: CI/CD for Service Users

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.5'

      - name: Install dependencies
        run: |
          go mod tidy
          go mod vendor

      - name: Run tests
        run: go test ./...

      - name: Build the application
        run: go build -o service-users ./cmd

      - name: Build Docker image
        run: |
          docker build -t smnrckrc/service-users:${GITHUB_SHA} .

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 565393060276.dkr.ecr.us-east-1.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Tag Docker image
        run: |
          docker tag smnrckrc/service-users:${GITHUB_SHA} 565393060276.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/service-users:${GITHUB_SHA}

      - name: Push Docker image to ECR
        run: |
          docker push 565393060276.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/service-users:${GITHUB_SHA}

      - name: Deploy to AWS EC2
        run: |
          ssh -i "${{ secrets.SSH_PRIVATE_KEY }}" ubuntu@50.16.42.75 "docker pull 565393060276.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/service-users:${GITHUB_SHA} && docker run -d -p 8080:8080 565393060276.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/service-users:${GITHUB_SHA}"
